language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

env:
  - DB=pgsql

before_script:
  - composer install --dev
  - psql postgres -c "CREATE ROLE root WITH LOGIN PASSWORD 'P@ssw0rd';"
  - psql postgres -c 'DROP DATABASE IF EXISTS tutorial;'
  - psql postgres -c 'CREATE DATABASE tutorial owner root;'
  - php cli migrate

script:
  - mkdir -p build/logs
  - cd application/tests
  - ../../vendor/bin/phpunit --coverage-text
  - cd ../../

after_script:
  - php vendor/bin/coveralls -v
